### ISSUE TITLE
Brilliant project, Feature request?

### ISSUE THREAD

**Issue by cwadrupldijjit** [ankurk91/vue-toast-notification#1]
So I think that this project is great!  It's simple and straightforward, too.  However, there are a few things that I feel could be good features on top of what's already implemented.

* [x] Add support for dismissing a toast programmatically, especially with a bulk dismiss function
* [ ] Add support for custom toast templates, so that a header and body could be used (Slots?)
* [ ]  Add support for other actions to exist on the toast
* [x] Add TypeScript support

Are any of these on the radar?  The TypeScript support shouldn't be hard to create, and I've created what _should_ work for dismissing all of the components (though it's using a property on an element that likely isn't supposed to be used for non-Vue-core code to access a component instance).  Would you appreciate PRs for some of these suggestions?

**Comment by ankurk91** [comment]
> 1. Add support for dismissing a toast programmatically, especially with a bulk dismiss function
It is possible to close a toast programmatically already.

```js
let toast = Vue.$toast.open('You did it!');
// dismiss
toast.close();
```
> 2. Add support for custom toast templates, so that a header and body could be used (Slots?)

Yes, We can use slots for template customisation.

> 3. Add support for other actions to exist on the toast

What are the other actions?

> 4. Add TypeScript support

I am not interested in learning any foreign language. (Not being rude)
Please don't send any PR related to TypeScript.

> 5. Dismiss all of toast at once

We can use vue event bus for it.

I am open to receive  PR for slots and event bus.
Thanks.

**Comment by cwadrupldijjit** [comment]
I wouldn't replace JS with TypeScript, if that's what you were wondering.  I was just talking about adding type definition files so that people using TypeScript can use it easier. If you'd prefer not, then I won't submit it to you.  Instead, I may end up adding type definitions to the DefinitelyTyped project.

Slots would mean a slight change in implementation, and upon reflection, it may not be the best fit.  We could potentially do a template system, but that starts to get complicated and would possibly require shipping with the compiler, which would make most apps bloated.  More discussion would be necessary before we could do that.

**Comment by ankurk91** [comment]
I would prefer DefinitelyTyped project as separate package that you owns.

Regarding slots:
One of my other package allows users to specify the slot in this way.

https://github.com/ankurk91/vue-loading-overlay/blob/c0fb278d9e66a4616edcc46a57a03a7a92be2e62/src/js/Component.vue#L13-L17

I am thing of these slots:
* title (optional)
* message (default)
* action (optional clickable button with callback)

**Comment by ankurk91** [comment]
Follow https://github.com/ankurk91/vue-toast-notification/issues/17
