### ISSUE TITLE
Feature request? A new callback function prop onDismiss which will always get invoked when toast is dismissed(automatically or by manual click)

### ISSUE THREAD

**Issue by nemeton-x** [ankurk91/vue-toast-notification#11]
I know there is a function prop called **onClose** but that gets called only when there is a manual click on toast. What I need in my project is a confirmation when my toast got dismissed.

Please let me know if you already have something that I can use or if you are open to a PR.
Thanks

**Comment by ankurk91** [comment]
I will work on this soon

**Comment by ankurk91** [comment]
Version 0.2.0 released

**Comment by nemeton-x** [comment]
thanks @ankurk91 , really appreciate the promptness.
Both callback options onClick & onClose look great and perfectly make sense.
