### ISSUE TITLE
Error in  $toast.open

### ISSUE THREAD

**Issue by FloteFuertes** [ankurk91/vue-toast-notification#13]
TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them at Function.invokeGetter

```js
     Vue.use(VueToast);
     

     var app = new Vue({
         el: '#app',
         data: {
             message: 'You loaded this page on ' + new Date().toLocaleString()
         },

         methods: {
             open() {
                 this.$toast.open({
                     message: "Test message from Vue",
                     type: "success",
                     duration: 5000,
                     dismissible: true
                 });
             }
         }
     })
 ```

**Comment by ankurk91** [comment]
Hi,

The example is working fine for me, check
https://jsfiddle.net/ankurk91/ebakcs62/

Please share your whole code, i am not sure how you are trying to use this component.

**Comment by FloteFuertes** [comment]
Hi,
I am using it in asp.net core  here is my Index cshtml
`<div id="app">
    <div class="text-center" >
        <h1 class="display-4">You are using @theme Theme</h1>
        <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
        <button type="button"  class="btn btn-primary" v-on:click="open">show</button>
        {{message}}
    </div>

</div>

@section Scripts {

    <script type="text/javascript">

        Vue.use(VueToast);

        var app = new Vue({
         el: '#app',
             data: {
                 message: 'You loaded this page on ' + new Date().toLocaleString()
             },

             methods: {
                 open() {
                     this.$toast.open({
                         message: "Test message from Vue",
                         type: "success",
                         duration: 5000,
                         dismissible: true
                     });
                 }
             }
      })
 </script>`
and I reference the scripts in my _Layout.cshtml

**Comment by ankurk91** [comment]
I dont think your issue is related to this library.

Please google this, here are some links to start

https://stackoverflow.com/questions/52298691/getting-typeerror-caller-callee-and-arguments-properties-may-not-be-acc

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode

**Comment by FloteFuertes** [comment]
I am just using same as what the example is given.  
Exception: TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them at Function.invokeGetter (<anonymous>:1:142) at Vue.open (https://localhost:5001/js/Vue/Toast.js:11:18) at invokeWithErrorHandling (https://cdn.jsdelivr.net/npm/vue/dist/vue.js:1863:28) at HTMLButtonElement.invoker (https://cdn.jsdelivr.net/npm/vue/dist/vue.js:2188:16) at HTMLButtonElement.original._wrapper (https://cdn.jsdelivr.net/npm/vue/dist/vue.js:7547:27)]

**Comment by ankurk91** [comment]
I am helpless my friend, the example in js-fiddle is working fine.
You can even clone this repo and play with `example` folder.
I am not aware of you environment.

You can even play more at 
https://codesandbox.io/
