### ISSUE TITLE
Add id to toast, auto overriding previous toast with same id

### ISSUE THREAD

**Issue by Tucsky** [ankurk91/vue-toast-notification#14]
Hello, thank you for this plugin, it is very light and get the job done quick.
I have one suggestion sir.

Its very common for web app to have recurrent messages (shown as toast), like errors occuring for the same reason (or related to), or steps in the app workflow that shows a toast for each step but it would be less overwhelming to override the previous toast if step get finished fast. Because it is related.

I would suggest to add an "id" property to the toast, optional of course, but if it is set and a toast already exists with the same id, immediately hide this previous toast and show new one.

I could try a PR if you agree that it could be a good addition.

**Comment by ankurk91** [comment]
@Tucsky 
Hi, thanks for the idea, yes you can try to send a PR, i would like to see your implementation first.
I would also like to see any existing similar toast plugin which does the same.

**Comment by Tucsky** [comment]
Well there was two plugin that pop out when I decided to add one to my app, vue-toasted and this one! I didn't actually checked to see if vue-toasted was doing the id feature before posting but just found out that it don't support that, which is surprising tbh.

Anyway, there you go, its for react but its doing the id thing https://github.com/fkhadra/react-toastify#use-a-custom-id

Imma try the pr then 👍

**Comment by ankurk91** [comment]
I will check in my day, thanks.

**Comment by ankurk91** [comment]
Follow https://github.com/ankurk91/vue-toast-notification/issues/17
