### ISSUE TITLE
add infinity duration or close toast until user click 

### ISSUE THREAD

**Issue by ayophanz** [ankurk91/vue-toast-notification#16]
add infinity duration or close toast until user click

**Comment by ankurk91** [comment]
For now you can manually pass a higher number.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER

**Comment by ankurk91** [comment]
Continued on

https://github.com/ankurk91/vue-toast-notification/issues/17
