### ISSUE TITLE
toast msg not show again after clear

### ISSUE THREAD

**Issue by ayophanz** [ankurk91/vue-toast-notification#18]
when I logout and clear toast, I login again toast won't show up even I declare toast open when trigger login

I figure it out what the cause is if queue is true

**Comment by ankurk91** [comment]
Heya,

The description is not enough to re-produce the issue.
It would be good if you can setup a minimal code base, or can write steps.

**Comment by ayophanz** [comment]
try to set duration something like 30000, make queue true  and then create
a function that can clear the toast and then create a function that re-open
the toast and bugs will show

**Comment by ankurk91** [comment]
Was able to re-produce the bug
https://jsfiddle.net/d2eun94q/2/

**Comment by ayophanz** [comment]
that is correct but mine is weird, my bug is when you queue true and
clear(logout) the toast and login again toast will wait base on duration
before show up
export default {
    data() {
      return {
        loading: false,
        isModalShow: false,
        latestApp: [],
        toastSetup: {
          config: {
            message: this.$t('static.releaseNote.toast.message'),
            dismissible: true,
            duration: 6000,
            type: 'info',
            queue: true,
            onClick: this.onclick,
            container: null,
          },
        },
      };
    },

    computed: {
      ...mapGetters({
        account: 'account',
        toastResp: 'toastResp',
        latestAppVersion: 'latestAppVersion',
      }),
    },

    /**
    * Watch property
    */
    watch: {

      latestAppVersion(latestAppVersion) {
        this.latestApp = latestAppVersion.items;
        if (this.toastResp.items === false) this.isModalShow = false;
        this.checkToastShow(this.latestApp);
      },

      toastResp(toastResp) {
        if (toastResp.items === true) {
          this.isModalShow = true;
          this.modalReleaseNote();
        }
      },

      $route(to, from) {
        if (to.name !== 'auth.login' || to.path !== '/login') {
          if (from.name === 'auth.login' || from.path === '/login') {
            this.modalReleaseNote(false, true); ---> when login call the
function
          }
        } else {
          this.$toast.clear(); ----> this is when logout
        }
      },
    },

    methods: {

      /**
       * Toast onclick
       */
      onclick() {
        this.$toast.clear();
        Promise.resolve(accountService.updateUserAppToast('true')).then(()
=> {
          location.reload(true);
        });
      },

      /**
       * Show up modal release note
       */
      modalReleaseNote(showModal = true, onLogin = false) {
        Promise.all([
          userAppVersionService.fetchUserAppVersion(),
        ]).then(() => {
          if (this.latestApp !== 'updated' && showModal === true) {
            this.isModalShow = false;
            setTimeout(() => this.activateModal(), 1500);
          }
          if (onLogin === true && this.latestApp !== 'updated') {
            this.$toast.open(this.toastSetup.config); -------> open toast
          }
        });
      },

      /**
       * Get toast if clicked respo
       */
      taostResponse() {
        Promise.all([
          userAppToastService.fetchUserAppToast(),
        ]).then(() => {});
      },

      /**
       * Check if toast msg show
       */
      checkToastShow(latestAppVersion) {
        if (this.isModalShow === false && latestAppVersion !== 'updated' &&
this.$store.state.auth.authenticated === true) {
          this.$toast.open(this.toastSetup.config);
        }
      },
    },

    /**
     * Fires when the app has been mounted
     */
    created() {
    },
  };

**Comment by ayophanz** [comment]
Is this fixed?

**Comment by ankurk91** [comment]
This should be fixed in version `0.3.0`

**Comment by ayophanz** [comment]
thank you, I explore this package to find bugs
