### ISSUE TITLE
can we use HTML on toast message?

### ISSUE THREAD

**Issue by haqisaurus** [ankurk91/vue-toast-notification#2]
can we use html on toast message like 
`Vue.$toast.error('<strong>Error</strong> required data name')`

**Comment by ankurk91** [comment]
@haqisaurus 
Unfortunately no, this is to prevent possible XSS.
I am thinking of other possibilities to do this, like slots.

**Comment by haqisaurus** [comment]
@ankurk91 

Thank you for helping me 👍
