### ISSUE TITLE
How can I use your library in component?

### ISSUE THREAD

**Issue by kentforth** [ankurk91/vue-toast-notification#22]
I installed the library
I added the library in main.js file like this:

```js
import VueToast from "vue-toast-notification";
import "vue-toast-notification/dist/theme-default.css";

Vue.use(VueAgile, VeeValidate, VueToast);
```

Then I tried to use library in component but it doesn't work:

```js
methods: {
deleteVideo(id) {
      VideoDataService.delete(id)
       
 .then(response => {
          this.videos = response.data;
          this.getAllVideos();
          this.$toast.open("You did it!");
        })
        .catch(function(error) {
          console.log(error);
        });
    },
}
```
**How can i use your library properly in component?**

**Comment by ankurk91** [comment]
I can not help unless you share proper details, do you see any error in console?

**Comment by kentforth** [comment]
@ankurk91 When I run the method I get this error:

![Screenshot_1](https://user-images.githubusercontent.com/17134421/84144676-dd178d00-aa82-11ea-8ddc-1d7b3146871a.jpg)

**Comment by ankurk91** [comment]
I am using the package in a vue-cli project. 
```js
import VueToast from 'vue-toast-notification';

Vue.use(VueToast, {
  duration: 5000,
  type: 'default'
});
```

i never faced such issue

**Comment by ankurk91** [comment]
You can play with it here

https://codesandbox.io/s/competent-bash-lqtxe?file=/src/App.vue

**Comment by kentforth** [comment]
I added this thing to main.js file :
```
Vue.use(VueToast, {
  duration: 5000,
  type: 'default'
});
```

and notification is working. But toast notification is too big and icon is too small.
**Where I can fix it?**

![Screenshot_1](https://user-images.githubusercontent.com/17134421/84153394-04288b80-aa90-11ea-96f4-e7b422d5403d.jpg)

**Comment by haizad** [comment]
Hi, sorry I just felt to reopen this issue. I got '$toast' of undefined when I imported VueToast inside main.js.

main.js
```
import VueToast from 'vue-toast-notification';
import "vue-toast-notification/dist/theme-default.css";

Vue.use(VueToast, {
  duration: 5000,
  type: 'default'
});
```

other Vue component
```
this.$toast.open({
        message: 'Ops',
        type: 'error',
});
```
I got error of : 
'$toast' of undefined

I don't want to import VueToast codes inside Vue component , instead just import it on main.js. Please advise. Thank you.

**Comment by ankurk91** [comment]
@ haizad 
Are you using Vue v2.x ?

You need to put this line `Vue.use(VueToast)`, before `new Vue()` statement.
