### ISSUE TITLE
Text separated per alphabet, not per words 

### ISSUE THREAD

**Issue by ezmemoar** [ankurk91/vue-toast-notification#24]
```
[x] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[ ] Other, please describe
```

**MY PLATFORM**
* Vue.js version : 2.6.11
* Browser name and version : Chrome Latest
* This package version : 0.4.0

**DESCRIPTION**

Example, If the text in the notification are too long, it will separated per alphabet that will look like this:

```
**Mail has been sent. Check your em
ail for activate your account.**
```

But the text should be separated per words like this:

```
**Mail has been sent. Check your
email for activate your account.**
```

**Comment by ankurk91** [comment]
must be fixed in version 0.4.1
