### ISSUE TITLE
Toast height broken in bootstrap 4.5.1+

### ISSUE THREAD

**Issue by egrekov** [ankurk91/vue-toast-notification#26]
```
[X] Bug report 
```
* vue 2.6.11
* Browser name and version : Chrome 84.0.4147.105 
* This package version : 0.4.1

**Current behavior**
When updating bootstrap to version 4.5.2, the height of the toast became 350px. If you roll back bootstrap to version 4.5.0, the toast becomes normal size.

**Minimal reproduction of the problem with instructions**
Investigation has shown that in bootstrap 4.5.1+ the .toast class has a property flex-basis: 350px;
Native bootstrap toast renders correctly.

**Comment by ankurk91** [comment]
Thanks for reporting, it should be fixed in v0.5.0

**Comment by egrekov** [comment]
@ankurk91 Thank you so much, updated to 0.5.0, the problem is really gone, now again beautiful toasts.
