### ISSUE TITLE
styling issue

### ISSUE THREAD

**Issue by Kqula** [ankurk91/vue-toast-notification#28]
**I'm submitting a request of help with styling**  

I have just installed this great toaster (npm install vue-toast-notification --save). Mechanism works great just like on jsfiddle( https://jsfiddle.net/ankurk91/ebakcs62/). But I would like to have great styling like on demo ( https://ankurk91.github.io/vue-toast-notification/). As far as I understand styles should be included by ` import 'vue-toast-notification/dist/dist/theme-default.css';`. Problem is that this line gives me errors "Module not found: Error: Can't resolve 'vue-toast-notification/dist/dist/theme-default.css' in...." 

another thing is that
 `Vue.use(VueToast, {
    position: 'bottom-right'
  });`
does not work for me... what ever I try with postion it does not affect message ;/

Any ideas?

**Comment by Kqula** [comment]
worked it out.... just wrong placement. For me correct one was `import 'vue-toast-notification/src/themes/default/index.scss';`

**Comment by ankurk91** [comment]
The correct path is

```
import 'vue-toast-notification/dist/theme-default.css'
```
