### ISSUE TITLE
Is there a typescript version for this library?

### ISSUE THREAD

**Issue by true-eye** [ankurk91/vue-toast-notification#29]
**I'm submitting a ...**  (check one with "x")
```
[ ] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[x] Other, please describe
```

Is there a typescript version for this library?
I couldn't find `@types/vue-toast-notification`

Please let me know
Thanks in advance,

**Comment by ankurk91** [comment]
`No`
