### ISSUE TITLE
Using Toast in service file causes an error.

### ISSUE THREAD

**Issue by nirav2410** [ankurk91/vue-toast-notification#3]
Hi Ankur,
Thank you for this awesome plugin.

I want to to use toast for Axios responses in one of my service.ts file

this is my code:
main.ts
```ts
import Vue from 'vue';
import VueToast from 'vue-toast-notification';
import 'vue-toast-notification/dist/index.css';
Vue.use(VueToast, {
  position: 'bottom',
  duration: 5000,
  queue: true,
});
```

httpservices.service.ts

```ts
import Vue from 'vue';
class HttpService {
    private request (method: string, url: string, data?) {
        return axios
          .request({
            method,
            url,
            data,
          })
          .then((response) => {
              Vue.$toast.success('success');
              return response;
          })
          .catch((error) => {
              Vue.$toast.error(error.response.data.errors);
          });
    }
}

```
Error:
Property '$toast' does not exist on type 'VueConstructor<Vue>'.

also tried. this.$toast.error but same error.

**Comment by ankurk91** [comment]
Can you setup a https://codesandbox.io/
and reproduce the error

**Comment by ankurk91** [comment]
I was able to setup a code-sandbox
https://codesandbox.io/s/vue-toast-p57y7

It is not using type script but plain javascript, it is working fine for me.
Feel free to re-open.

**Comment by nirav2410** [comment]
It's not issue with showing the message.
Toast is showing with TS too. but it in Visual Code, it's showing linting error in terminal.
screenshot here.

https://drive.google.com/open?id=1AX9vRnCA6_8l5tgAeXGIWqL1b2DraoPJ

**Comment by ankurk91** [comment]
Linting is not my issue. I think you can type hint it somewhere.

**Comment by nirav2410** [comment]
You didn't have included declaration file as instructed by Vue with Typescript.

https://vuejs.org/v2/guide/typescript.html

Hence, I'd to add following code into project's main.ts

`declare module 'vue/types/vue' {
  interface VueConstructor {
    $toast: any
  }
}`

**Comment by ankurk91** [comment]
I am not going to learn type script, sorry.

feel free to publish the declarations
https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html
