### ISSUE TITLE
Css Naming feature request

### ISSUE THREAD

**Issue by LanFeusT23** [ankurk91/vue-toast-notification#31]
```
[ ] Bug report => search github for a similar issue or PR before submitting
[ X] Feature request
[ ] Other, please describe
```

**Tell about your platform**
* Vue.js version : 2.6.12
* Browser name and version : Chrome|Firefox|Safari x.x.x
* This package version : 0.5.4

**Current behavior**
When using post css to purge unused css classes, we have to add the following classes to the whitelist:
```
[
    /v-notices.+$/,
    /v-toast.+$/,
    /fade.+$/,
    /is-.+$/,
]
```

It would be really great if this package used BEM conventions. This way we wouldn't need multiple css classes to white list but just anything starting with `v-notices`!

**Comment by ankurk91** [comment]
@rishabhrpg

This issue is also a good candidate for PRs 😄
