### ISSUE TITLE
Vue 3 support?

### ISSUE THREAD

**Issue by swaprenge** [ankurk91/vue-toast-notification#32]
**Tell about your platform**
* Vue.js version : ^3.0.0
* Browser name and version : Chrome|Firefox|Safari x.x.x
* This package version : 0.5.4

**Current behavior**
This plugin works fine with vue version < 3.0.0

**Expected behavior**
Upgraded to Vue3 and `Vue.extend` is not supported in Vue3.
Also, the way to use the plugin in Vue3 is changed.

**Minimal reproduction of the problem with instructions**
- Upgrade to Vue version 3.0.0.

@ankurk91  Can you please help me with this?

**Comment by italocassio** [comment]
Any position about support vue 3?

**Comment by Alehandro231** [comment]
No support, just tried to install the plugin and got an error:

```
Uncaught TypeError: a is not a constructor
```

**Comment by ankurk91** [comment]
Unless I get enough time to upgrade this package for Vue 3.x, One can opt-in to go for 
https://github.com/Maronato/vue-toastification/tree/next

**Comment by ankurk91** [comment]
Made some progress on `next` branch

* [ ] Update docs
* [ ] Test case
* [ ] Type definitions
* [ ] Extract `setupContainer` login outside
* [ ] Fix the queue feature
* [ ] Change log
* [ ] Upgrade guide

**Comment by bhavinjr** [comment]
@ankurk91 Do we have a toast transition option?
if not then can we go with it to the next branch?

**Comment by ankurk91** [comment]
@bhavinjr 
Yes, we have it already

**Comment by bhavinjr** [comment]
@ankurk91 That's great.
can you please give the all transition option/effect. as of now, I didn't find it in the document

```
Vue.$toast.open({
    message: 'Something went wrong!',
    type: 'error',
    transition: 'bounce' // all transition effect
});
```

**Comment by ankurk91** [comment]
I meant it there but you can customize it
https://github.com/ankurk91/vue-toast-notification/blob/3043646c7cce982e66cf797d86ccdc377763272e/src/js/Component.vue#L3

**Comment by rojadesign** [comment]
@ankurk91 Do you have a specific date when you will publish the Vue 3 version? I ask because I see you have a _next_-branch. We need to evaluate if we can stick to this beautiful plugin or look for alternatives because we have some time pressure. Thank you so much for all your work!

**Comment by ankurk91** [comment]
Hey, thanks for reaching out.

I can publish the beta ttomorrow , my morning.

**Comment by ankurk91** [comment]
@rojadesign 

Version 2.0 beta has been published

**Comment by bhavinjr** [comment]
> I meant it is there but you can not customize it
> https://github.com/ankurk91/vue-toast-notification/blob/3043646c7cce982e66cf797d86ccdc377763272e/src/js/Component.vue#L3

Can you plan for this feature in the next publish if possible?

**Comment by ankurk91** [comment]
I can not promise.
