### ISSUE TITLE
Replace event bus with mitt 

### ISSUE THREAD

**Issue by ankurk91** [ankurk91/vue-toast-notification#33]
### Goal:
* Make this package ready for vue.js 3.x
* However, We are NOT targeting for vue 3.x now

### Notes:
* Remove Vue event bus and replace with [mitt](https://github.com/developit/mitt)
* Public API would be the same, this is not a breaking change for users.
* Event name would be the same as before `toast.clear`
* `mitt` will be bundled with package itself, so it should be a dev-dependency.
* There should not be any change in webpack configs or test cases.

//cc @rishabhrpg

**Comment by jprodrigues70** [comment]
Event name should be as the Vue 3x spec and use kebab-case. So... `toast-clear`.

**Comment by ankurk91** [comment]
Umm, this event is for internal communication only.
However we can still change it to kebab case.
