### ISSUE TITLE
Help Icons

### ISSUE THREAD

**Issue by LucasPanetto** [ankurk91/vue-toast-notification#42]
Hi, I'm trying to use the library, but I'm having problems rendering the icons in the alert.

![image](https://user-images.githubusercontent.com/25806409/98277733-708fb400-1f76-11eb-84f5-cdfbb21afd56.png)

![image](https://user-images.githubusercontent.com/25806409/98277748-74233b00-1f76-11eb-9898-78c345ca9a5e.png)

The warning icon is not displayed

**Comment by ankurk91** [comment]
Please use the sugar theme, it has icons.
