### ISSUE TITLE
Feature request: No duration & embedding Vue component

### ISSUE THREAD

**Issue by StrikeAgainst** [ankurk91/vue-toast-notification#43]
I just recently started using this plugin and I really quite like it, though it still lacks a bunch of features and options in my opinion. Two of those features which I personally would require are:

1. No duration: There are some cases where you'd want to have messages sticking out and staying visible until the user interacts with it - this of course should force the dismissible option, and maybe also provide a close icon for more intuitive design.
2. Embedded Vue components: Since we're already dealing with Vue here, why not make the toasts be able to render Vue components inside them as well?

**Comment by ankurk91** [comment]
duplicate of https://github.com/ankurk91/vue-toast-notification/issues/17
