### ISSUE TITLE
Heroku deploy failed

### ISSUE THREAD

**Issue by yannicklescure** [ankurk91/vue-toast-notification#44]
Did someone use this plugin on Heroku ? On localhost, it works perfectly. On production, deploy pass but nothing happens. No errors, the text is displayed but no toast at all. Is the path to the css file correct in the documentation ?

**Comment by ankurk91** [comment]
This plugin has nothing to do with heroku.
Check your webpack configuration

**Comment by yannicklescure** [comment]
Actually, the plugin doesn't work on Heroku as is. I had to move the plugin stylesheets and icons files to my app to make it works.
For reference, I use rails 6 with webpacker.

**Comment by ankurk91** [comment]
Try to generate production build on your local machine, and test your app. 

Your webpack solution might be using something like purge css, if yes then you need to whitelist this plugin css classes.


Stop referencing Heruko, it has nothing to do with css. 
If it works on your local machine, then it should also work your server.
