### ISSUE TITLE
NOT WORKING AT ALL

### ISSUE THREAD

**Issue by humoyun** [ankurk91/vue-toast-notification#47]
```
[ ] Bug report => no error, silently showing nothing

```

**Tell about your platform**
* Vue.js version : 2.6.11
* Browser name and version : Chrome|Firefox|Edge x.x.x
* This package version : 0.6.0

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**Comment by ankurk91** [comment]
Hey, this was not helpful. Please give more insights.

Did you import the css?
