### ISSUE TITLE
Guide: How to use with NuxtJS?

### ISSUE THREAD

**Issue by rutcreate** [ankurk91/vue-toast-notification#48]
I think it would be a great idea to put how to install with NuxtJS.

Create file `./plugins/vue-toast-notification.js` with code below.
```js
import Vue from 'vue'
import VueToast from 'vue-toast-notification'
import 'vue-toast-notification/dist/theme-sugar.css'

Vue.use(VueToast)
```

Add plugins to `nuxt-config.js`

```js
plugins: [
  ...,
  { src: '~/plugins/vue-toast-notification.js', mode: 'client' }
]
```

**Comment by ankurk91** [comment]
I never tried this in Nuxt.js, do you see any error?

**Comment by rutcreate** [comment]
> I never tried this in Nuxt.js, do you see any error?

Everything works fine!!. I just want to share how to use with NuxtJS. Feel free to use above as a documentation.

**Comment by Ouldev** [comment]
I have the same code but I get "Vue is not defined" .

**Comment by Abolfazl2049** [comment]
dosent work
