### ISSUE TITLE
[Proposal] More toast themes 

### ISSUE THREAD

**Issue by dimitor115** [ankurk91/vue-toast-notification#5]
Hi! This is a really great library, with high-quality codebase in my opinion.
I was thinking about writing my own toast library, before I found this one. Now I would like to help you with the development. I have some great ideas for new features, for example I think that it would be great to ship this package with a few themes available, so users can choose which one suits their needs.
I've prepared some proposal for other toast design than the default one:
![toast-1](https://user-images.githubusercontent.com/3342963/70396410-122a2080-1a09-11ea-932d-4fde0f7f2c64.png)
Let, me know what do you think about it! :smile_cat:

**Comment by dimitor115** [comment]
@ankurk91  I can prepare PR if you would like!

**Comment by ankurk91** [comment]
@dimitor115 
Please do, i am happy to review it

**Comment by dimitor115** [comment]
@ankurk91 I hope to do it, in a next few days :smile:

**Comment by ankurk91** [comment]
Closed with version `0.1.0`
