### ISSUE TITLE
Stable Release?

### ISSUE THREAD

**Issue by griffincox** [ankurk91/vue-toast-notification#50]
**I'm submitting a ...**  (check one with "x")
```
[ ] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[x] Other, please describe
```

I see that the latest version is 0.6.1. Are you following semantic versioning? If so, a version <1 would suggest that this package is not yet stable. Any idea when you'll be at a v1.x release?

**Comment by ankurk91** [comment]
Hey,

The package is stable enough.
I have no plans to add more features to this package for now.
