### ISSUE TITLE
Support only 1 toast show.

### ISSUE THREAD

**Issue by finnpham** [ankurk91/vue-toast-notification#52]
**What about have only 1 toast each time show?**
- My expect is: If have previous toast => closed it immediately and open new toast. 

Because:

> Now i using clear() before open new event. => it work. but still have ghosting previous toasts (because animations fadeIn).  This make bad UX :( 

This case help mobile UX well.

Thanks so much!

**Comment by ankurk91** [comment]
There is a `queue` option which let new toast wait for previous toast to close

**Comment by finnpham** [comment]
> queue

no, i means, when have new toast create => it clear old toast. 

`queue` option => Wait for existing to dismiss before showing new. @ankurk91

**Comment by ankurk91** [comment]
I would suggest to go for this library
https://github.com/Maronato/vue-toastification

**Comment by finnpham** [comment]
@ankurk91 , maybe i will make this option and PR for you?

**Comment by ankurk91** [comment]
@finnpham 
You can submit your PR,  i will merge if i found your implementation good.
