### ISSUE TITLE
Can we trigger a toast from vuex store action

### ISSUE THREAD

**Issue by Vidhyanandcs** [ankurk91/vue-toast-notification#53]
**I'm submitting a ...**  (check one with "x")
```

[x ] Question=> can i use this to trigger a toast from the vuex store.
```

**Tell about your platform**
* Vue.js version : 2.6.x
* Browser name and version : Chrome|Firefox|Edge x.x.x
* This package version : 0.x.x

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

we are using something like this in bootstrap vue

   `import { BToast } from 'bootstrap-vue'
    let bootStrapToaster = new BToast();
    bootStrapToaster.$bvToast.toast(error.response.data.message, {
      title: 'Error',
      variant: 'danger',
      solid: true
    })`

**Comment by ankurk91** [comment]
You suppose to post your query here

https://github.com/bootstrap-vue/bootstrap-vue
