### ISSUE TITLE
Provision to show long notifications in multiple lines

### ISSUE THREAD

**Issue by Vidhyanandcs** [ankurk91/vue-toast-notification#54]
**I'm submitting a ...**  (check one with "x")
```
[ ] Bug report => search github for a similar issue or PR before submitting
[X ] Feature request
[ ] Other, please describe
```

**Tell about your platform**
* Vue.js version : 2.6.x
* Browser name and version : Chrome|Firefox|Edge x.x.x
* This package version : 0.6.1

**Current behavior**
For very short notifications the toast looks good.  But for longer notifications the toast length increases. 

**Expected behavior**
The toast would look better if we can specify the max length of the toast so that the text will be shown in multiple lines if notification is little longer.

**Minimal reproduction of the problem with instructions**
![Capture](https://user-images.githubusercontent.com/11901913/115335307-90c8cd80-a1ba-11eb-8420-a816720d1a34.JPG)

**Comment by ankurk91** [comment]
The toast already allow you to pass html in message prop.

You can do it like
```
line one <br>
line two >br>
<b>line three</b>
```

or
you can customize the css the way you want. :man_shrugging:

**Comment by Vidhyanandcs** [comment]
I am getting the response from server. So i think CSS will be the right option.

Is there a better way?

**Comment by ankurk91** [comment]
You can override css for sure.


My major todo is to add support for vue 3 now

**Comment by Vidhyanandcs** [comment]
Can you point me the documentation for adding css

**Comment by ankurk91** [comment]
Seriously? It should be documented? 

Navigate to source and and find the right css class.

Then just add max width property in your code.

**Comment by Vidhyanandcs** [comment]
`.v-toast__item{
	max-width: 200px;
}`

worked for me. Thank you
