### ISSUE TITLE
Make useToast available from import

### ISSUE THREAD

**Issue by hermandsen** [ankurk91/vue-toast-notification#58]
**I'm submitting a ...**
```
[ ] Bug report => search github for a similar issue or PR before submitting
[x] Feature request
[ ] Other, please describe
```

**Tell about your platform**
* Vue.js version : 3.0.x
* This package version : next

**Current behavior**
The `$toast` object is only available in components, not from imports.

**Expected behavior**
I would be nice to have useToast available for in .ts files - for instance in Vuex.

_`example.ts`_
```javascript
import { useToast } from "vue-toast-notification";

useToast.success("Hello world.");
```

It should be as simple matter of exporting `{ useToast }` in `index.js` and changing the `.d.ts` file.

**Comment by ankurk91** [comment]
https://github.com/ankurk91/vue-toast-notification/blob/e5a598992b2935ab0077df14faa976a2b70ba8c4/src/index.js#L14

This is already being exported, but not documented 

Does this work for you?

**Comment by hermandsen** [comment]
Unfortunately it doesn't.
I don't know if it's webpack doing treeshaking, or something else, but if i do
````javascript
const toast = import('vue-toast-notification');
console.log(toast);
````
I don't get `useToast` as part of the object.

**Comment by ankurk91** [comment]
It is a named export. Should imported in same fashion. Google about it.

**Comment by hermandsen** [comment]
It doesn't work.

**Comment by hermandsen** [comment]
Try this code using vue-toast-notification@next on Vue 3.
````javascript
import * as toast from "vue-toast-notification";
console.log(toast);
````

This is the object you get in the browser:
````
Object { install: install(t, e) }
  install: function install(t, e)
    length: 1
    name: "install"
    <prototype>: function ()
  <prototype>: Object { … }
````

`useToast` is not part of the export when Vue is done building.

**Comment by ankurk91** [comment]
Looks like webpack is removing un used exports from bundle

https://unpkg.com/browse/vue-toast-notification@2.0.0/dist/index.js

Need to find a way to prevent this

**Comment by ankurk91** [comment]
fixed with 2.0.1

**Comment by ankurk91** [comment]
Looks like it not fixed 
https://github.com/webpack/webpack/issues/2933

**Comment by hermandsen** [comment]
Thanks for looking in to it.
Guess I wait for Webpack to fix the bug.

**Comment by ankurk91** [comment]
You can use composition api now with v3.x

```
import {useToast} from "vue-toast-notification";
```

**Comment by aurexs** [comment]
> You can use composition api now with v3.x
> 
> ```
> import {useToast} from "vue-toast-notification";
> ```


In typescript it marks an error, apparently the additional exports are not defined in the `toast.d.ts`:

`ts: Module '"vue-toast-notification"' has no exported member 'useToast'.`

**Comment by ankurk91** [comment]
Feel free to send a PR

**Comment by Arobce** [comment]
I am trying to use the `useToast` to show some errors in a .ts file.

Here is basically how I am doing it:

```
import axios, { AxiosInstance } from "axios";

import { useToast } from "vue-toast-notification";

const getApiClient = (): AxiosInstance => {
    return axios.create({
        baseURL: "https://api-url",
        headers: {
            "Content-type": "application/json",
        }
    });
}

const apiClient: AxiosInstance = getApiClient();

apiClient.interceptors.response.use((response) =>
    response
    , (error) => {
        useToast.error(error);
        throw error;
    });

export default apiClient;
```

I am getting this error:

`TypeError: useToast.error is not a function
`

I have no idea what is causing this. Any help or a point in the right direction would be greatly appreciated.

**Comment by ankurk91** [comment]
You suppose to do it like this

```js
useToast().error(error);
```
