### ISSUE TITLE
vue-toast-notification:1 Uncaught TypeError: (0 , t.createVNode) is not a function

### ISSUE THREAD

**Issue by disapamok** [ankurk91/vue-toast-notification#59]
Recently the plugin is throwing this "vue-toast-notification:1 Uncaught TypeError: (0 , t.createVNode) is not a function" error.
I am using CDN with VueJS 2 CDN. 

My whole code is broken now.
![Capture](https://user-images.githubusercontent.com/7949612/131813555-390bf596-2885-4f3e-a68d-44ae637558d6.JPG)

**Comment by ankurk91** [comment]
What is your CDN url?

It should look like this.

```html
<!-- Vue.js -->
<script src="https://cdn.jsdelivr.net/npm/vue@2.6"></script>
<!-- Lastly add this package -->
<script src="https://cdn.jsdelivr.net/npm/vue-toast-notification@0.6/dist/index.min.js"></script>
<link href="https://cdn.jsdelivr.net/npm/vue-toast-notification@0.6/dist/theme-sugar.css" rel="stylesheet">
<!-- Init the plugin -->
<script>
    Vue.use(VueToast);
</script>
```

The readme is outdated.

Please fill issue template to get proper support.

**Comment by aeadedoyin** [comment]
![image](https://user-images.githubusercontent.com/20503883/132254137-16240b3a-371c-4d5f-a5eb-dbe8935b0246.png)

This is still happening.

NuxtJS Plugin
```js
import Vue from 'vue'
import VueToast from 'vue-toast-notification'

Vue.use(VueToast, {
  position: 'bottom',
  queue: true,
  duration: 3500
})
```

**Comment by ankurk91** [comment]
You did not fill issue template properly yet

**Comment by aeadedoyin** [comment]
**I'm submitting a ...** 
```
[x] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[ ] Other, please describe
```

**Tell about your platform**
* Vue.js version : 2.6.x
* Nuxt 2.15.x
* Browser name and version : Chrome 93.0.4577.63
* This package version : 2.0.1

**Current behavior**
![image](https://user-images.githubusercontent.com/20503883/132254137-16240b3a-371c-4d5f-a5eb-dbe8935b0246.png)

This(OP) is still happening.

In the NuxtJS Plugin setup.
```js
import Vue from 'vue'
import VueToast from 'vue-toast-notification'

Vue.use(VueToast, {
  position: 'bottom',
  queue: true,
  duration: 3500
})
```

Everyother thing done just the way it should. The error just started from v2.0.1

**Comment by ankurk91** [comment]
The readme has this version matrix, you must read it properly.


### Version matrix

| Vue.js version | Package version | Branch        |
| :---           | :---:           | ---:          | 
| 2.x            | 1.x             | [1.x](https://github.com/ankurk91/vue-toast-notification/tree/v1.x) |
| 3.x            | 2.x             | `master`          |

You are using vue v2.x, you should older version of this packeg

```
# yarn
yarn add vue-toast-notification@^0.6

# npm
npm install vue-toast-notification^0.6
```

**Comment by aeadedoyin** [comment]
But I strongly feel going that route makes 2.0.1 the default. 
Hence for every new installation, one has to add the 1.x version. 

Bare in mind a whole lot of users still use 2.6.

**Comment by ankurk91** [comment]
I don't care what whole lot of users doing, i have documented the things, those whole lot of users should learn how to read docs first.
