### ISSUE TITLE
Overriding colors

### ISSUE THREAD

**Issue by LenaertsJ** [ankurk91/vue-toast-notification#63]
**I'm submitting a ...**  (check one with "x")
```
[ ] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[x] Question
```

**Tell about your platform**
* Vue.js version : 3
* Browser name and version : Firefox
* This package version : 2.0.1

Hi Ankurk,

I was just wondering, is there an easy way to override the colors used for the toasts?
I'm fairly new to web development, but working on a project now where we would like to use the application color scheme for the toasts as well.

Thanks for this plugin, it's great :-) 
Any help with the colors would be aweome too!

Cheers!

**Comment by ankurk91** [comment]
The package is using scss, and you can override variables for any of theme, for example

https://github.com/ankurk91/vue-toast-notification/blob/master/src/themes/default/_variables.scss
