### ISSUE TITLE
Help to override color

### ISSUE THREAD

**Issue by power-cut** [ankurk91/vue-toast-notification#65]
I am trying to override the css colors, so far no success.
Please provide the steps to make the changes, 

Thanks

**Comment by ankurk91** [comment]
https://github.com/ankurk91/vue-toast-notification/issues/63

**Comment by power-cut** [comment]
I have tried to import the variable file in a custom scss file and then to override the css.
I'm unable to override it.

**Comment by ankurk91** [comment]
Share your code or create a codesandbox

**Comment by power-cut** [comment]
```
//custom.scss file
@import "~vue-toast-notification/src/themes/default/_variables.scss";

$toast-colors: (
    success: #333745,
);

```

**Comment by ankurk91** [comment]
Please learn scss first.

You need to define the variable first and then consume it.

**Comment by power-cut** [comment]
Thanks, but it will be much better to help the fellow developers with clear steps and then close the ticket.

**Comment by ankurk91** [comment]
There are tons of resource on Internet to learn scss.

**Comment by kimkyeseung** [comment]
hi is it same to version 0.6??? I'm using vue 2 now

plz answer me

**Comment by ankurk91** [comment]
Yup same
