### ISSUE TITLE
toast underneath modal popups.

### ISSUE THREAD

**Issue by stealthrabbi** [ankurk91/vue-toast-notification#66]
**I'm submitting a ...**  (check one with "x")

If I have a modal dialog up and go to show a toast, the toast is underneath the modal. My modal has  these properites in the outer div. Is there  a way to control the Z-order?

``` html
    <div
      class="modal fade d-block show"
      id="myModal"
      tabindex="-1"
      aria-labelledby="exampleModalLabel"
      aria-hidden="true"
    >
    ```

**Comment by ankurk91** [comment]
Feel free to override the css

https://github.com/ankurk91/vue-toast-notification/blob/58ff22db00d9b471429da878c9e1d72800f0f4cb/src/themes/default/_main.scss#L10

**Comment by stealthrabbi** [comment]
Thanks yup, I was tinkering with this after I posted. I ended up making my own css w\:

```
.v-toast {
    z-index: 2000 !important
}
```

thank you.
