### ISSUE TITLE
Getting Error while using component

### ISSUE THREAD

**Issue by saijayaprakash** [ankurk91/vue-toast-notification#67]
I know it might be a rookie mistake. But i am getting this while using this component @vue 3. Just followd the NPM doc. No use.
![image](https://user-images.githubusercontent.com/18374743/160682022-2d23d713-5edd-4a1b-9066-36e953b74fc1.png)

**Comment by ankurk91** [comment]
I have full rights to close this issue since you did not fill out issue template.
You need to learn to respect maintainer time's value.
