### ISSUE TITLE
vue-toast-notification not working in production

### ISSUE THREAD

**Issue by petersjeroen** [ankurk91/vue-toast-notification#7]
First of all my sincere congratulations on these very nicely designed notifications! 

After having tested my application locally for a long time, the application has recently gone into production. But now it looks like nothing happens when I try to trigger a notification. Even no console error messages...

## Steps to reproduce
1. Make a new test project via the vue CLI
2. Integrate vue-toast-notification as explained in the README
3. Run `npm run build`
4. Move the contents of the `dist` folder to a test website (e.g. via FTP)
5. Try to trigger the notification

## Result
Nothing happens

**Comment by ankurk91** [comment]
This is no where helpful as a developer.
Please provide sample code or  a reproduction
