### ISSUE TITLE
[vue-2] Error "Generic type 'ExtendedVue' requires 6 type argument(s)

### ISSUE THREAD

**Issue by Thomas-1985** [ankurk91/vue-toast-notification#76]
**I'm submitting a ...**  (check one with "x")

```
[x] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[ ] Other, please describe
```

**Tell about your platform**

* Vue.js version : 2.6.11
* Browser name and version : Firefox 102
* This package version : 0.6.2

**Current behavior**
There is an error on `npm run build` when i try to compile my project
```
ERROR in /.../frontend/node_modules/vue-toast-notification/types/toast.d.ts(4,41):
4:41 Generic type 'ExtendedVue' requires 6 type argument(s).
    2 | import {PluginFunction} from 'vue'
    3 |
  > 4 | export interface ToastComponent extends ExtendedVue<any, any, any, any, any> {
      |                                         ^
    5 |   dismiss(): void
    6 | }
    7 |
```

**Expected behavior**
There should be no error

**Minimal reproduction of the problem with instructions**

**Comment by ankurk91** [comment]
Fixed in v0.6.3
