### ISSUE TITLE
Change duration milliseconds to seconds

### ISSUE THREAD

**Issue by xon52** [ankurk91/vue-toast-notification#8]
I love how small this is, good work. Can we change milliseconds to seconds though? Seems unlikely someone would use milliseconds, and if they do they still can with a decimal - but most would just use seconds.

I've already made changes if I can make a pull request.

**Comment by ankurk91** [comment]
Thanks for appreciation. 😄 
I am following other similar libraries, for example

https://buefy.org/documentation/toast/
https://github.com/shakee93/vue-toasted

So most libraries are using `milliseconds `
