### ISSUE TITLE
To push dynamic data in message prop

### ISSUE THREAD

**Issue by PiseAtharva** [ankurk91/vue-toast-notification#82]
**I'm submitting a**  (check one with "x")

- [x] (Feature request)

**Tell about your platform**

* Vue.js version : 3.2.37
* Browser name and version : Chrome
* This package version : 3.0.4

**Current behavior**

I wanted to know if we can pass a data variable in the message attribute for example - 
```js
this.$toast.open({
        :message: "dynamicVariable",
        type: "success",
        duration: 3000,
        dismissible: true,
        position: "top-right",
      })
```
 so as to make it bit dynamic in nature. Statically it works like a charm, really smooth to establish.

**Comment by ankurk91** [comment]
Yes, you can,

Please go and learn some basic JS concepts.

**Comment by PiseAtharva** [comment]
can i ask how, a rough idea can also help

**Comment by ankurk91** [comment]
I really don't understand what you are asking for. i am sorry but i dont have time to teach JS on GitHub.

```js
this.$toast.info(ANY_VARIABLE_THAT_HAS_STRING_VALUE);
```

**Comment by PiseAtharva** [comment]
I can repeat myself (no issue with that), I want to use your this.$toast.open function with the message attribute set to a variable
