### ISSUE TITLE
nuxt 3 module

### ISSUE THREAD

**Issue by joseehilton147** [ankurk91/vue-toast-notification#83]
**I'm submitting a ...**  (check one with "x")

```
[ ] Bug report => search github for a similar issue or PR before submitting
[x] Feature request
[ ] Other, please describe
```

Its possible to make this works on nuxt 3 as module or show us a integration using the new plugin system please.

**Comment by ankurk91** [comment]
I have no idea of nuxt 3 and their plugin system

**Comment by itskush** [comment]
I got you
Do this.


Create a file in your plugins folder such as toaster.ts
paste the following in there: 
```
import { useToast } from 'vue-toast-notification';
const toast = useToast();
export default defineNuxtPlugin(() => {
    return {
      provide: {
        toast,
      }
    }
});
```

in your nuxt.config.js add this to your css array 
`'vue-toast-notification/dist/theme-default.css'`

to use the toaster in your component now do this

```
const { $toast } = useNuxtApp();
 $toast.success('You did it!');
```

have fun!!

**Comment by coolpi21** [comment]
> const { $toast } = useNuxtApp();
>  $toast.success('You did it!');

There will be an error in preview mode because named export 'useToast' not found.
