### ISSUE TITLE
toast notification falling behind the the dialog element

### ISSUE THREAD

**Issue by vaheqelyan** [ankurk91/vue-toast-notification#89]
**I'm submitting a bug**

```
[ x] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[ ] Other, please describe
```

**Tell about your platform**

* Vue.js version : 3.2.x
* Browser name and version : Chrome
* This package version : 3.x

**Current behavior**
I have an HTML5 dialog element with a backdrop featuring a blur filter. However, when attempting to display a toast message, it fails to appear as the toast notification falls behind both the backdrop and the dialog element.

![image](https://github.com/ankurk91/vue-toast-notification/assets/14107127/61b37568-248a-49b8-a89a-a3707a56b19b)

**Expected behavior**
Can we ensure that the toast notifications are not covered by the backdrop?

**Minimal reproduction of the problem with instructions**
[codesandbox](https://codesandbox.io/s/frosty-curran-xlmhgm?file=/src/App.vue)

**Comment by ankurk91** [comment]
Please search for existing similar issues

**Comment by vaheqelyan** [comment]
Hello, I've already searched for similar issues but couldn't find any. Your help would be greatly appreciated.
https://github.com/ankurk91/vue-toast-notification/issues/88 this is the only issue i found, but `dialog` does not care about z-index

**Comment by ankurk91** [comment]
https://stackoverflow.com/questions/41815069/is-it-possible-to-position-a-div-on-top-of-a-dialog-tag-that-is-not-its-parent


The <dialog> element is added to the 'Top Layer' of the DOM which has its own stacking order (z-index does not affect this

**Comment by vaheqelyan** [comment]
Hey, thanks for the link, but I'm a bit confused. I couldn't really make sense of how it's related to the issue I brought up.

> The element is added to the 'Top Layer' of the DOM which has its own stacking order (z-index does not affect this

Sure that's the issue. I may look for other packages, but I'm concerned they may face the same issue.
