### ISSUE TITLE
Hot Module Reload breaking on nuxt 3 vue 3 with Pinia

### ISSUE THREAD

**Issue by idlethumbs** [ankurk91/vue-toast-notification#90]
**I'm submitting a ...**  (check one with "x")

```
[ x] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[ ] Other, please describe
```

**Tell about your platform**

* Vue.js version : 3.3.x
* Browser name and version : Chrome|Firefox|Edge 
* latest chrome
* This package version : 3.1.2
*  "nuxt": "^3.9.0",
* pinia: ^2.1.7

**Current behavior**

when importing useToast; HMR stops working in my nuxt app, browser refresh must be forced, 
HMR updates still appear in the terminal.

upon removing the line with `import {useToast} from 'vue-toast-notification'`
and restarting server HMR starts working again as expected.
```ts
<script setup lang="ts">
import { useToast } from 'vue-toast-notification';
</script>
```
**Expected behavior**

HMR is not affected by importing useToast

**Minimal reproduction of the problem with instructions**
Upon investigation - discovered this due to versioning conflicts,

Pinia [documentation](https://pinia.vuejs.org/ssr/nuxt.html) suggests adding :
```
"overrides": {
  "vue": "latest"
}
``` 

to `package.json` for nuxt apps. This seems to cause HMR to break when using vue-toast-notifications.
updating to leave vue-toast-notification dependencies unchanged:

```
  "overrides": {
    "vue": "latest",
    "vue-toast-notification": {
      "vue": "^3.0"
    }
  },
  ```
  
  fixes the issue and HMR works again
  
  I'm not sure whether to update pinia fix to apply only to pinia (e.g. "pinia": { "vue" : "latest" }) or do the above, both will work but I believe the pinia scoped latest only results in more versions of vue in the project than necessary.

**Comment by ankurk91** [comment]
Right now, I dont have time to re-produce the issue

**Comment by idlethumbs** [comment]
@ankurk91 
when i have time i will create a repo with minimum repro, it should be a fresh nuxt app (npx nuxi init) and then adding the vue version override that pinia asks for, we shouldn't need to install pinia to re-create the problem, but i can add it as it's relevant.
