### ISSUE TITLE
Toaster zIndex

### ISSUE THREAD

**Issue by bitblitz4use** [ankurk91/vue-toast-notification#96]
Hi there, 
is it possible to set the zIndex of the toaster globally with API? 
Using Vue 3

Thx

**Comment by bitblitz4use** [comment]
I tried it with 

`.vue-toast-notification {
    z-index: 9000 !important;
  }`

inside an imported global scss file. 
Is the class name right? Sorry could not find css class names in docu

**Comment by ankurk91** [comment]
https://github.com/ankurk91/vue-toast-notification/blob/2bf6e843d64d798cf472eb37a7eb8396b5a7551b/src/themes/default/_main.scss#L10
