### ISSUE TITLE
Warning Failed to load source map on dev server run

### ISSUE THREAD

**Issue by Ricro** [ankurk91/vue-toast-notification#97]
**I'm submitting a ...** 

```
[x] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[ ] Other, please describe
```

**Tell about your platform**

* Vue.js version : 3.5.10
* Browser name and version : Chrome 129.0.6668.90
* vue-toast-notification version : 3.1.3
* Vite version : 5.4.8
* Nuxt version : 3.13.2
* Bun version : 1.1.29

**Current behavior**
When I launch the development server, I get the following warning : 
```
WARN  Failed to load source map for /node_modules/vue-toast-notification/dist/index.js.                                                             
Error: An error occurred while trying to read the map file at mitt.mjs.map
Error: ENOENT: no such file or directory, open '/node_modules/vue-toast-notification/dist/mitt.mjs.map'
```

This warning doesn't prevent me to use this package in my project.

**Expected behavior**
No warning at all

**Minimal reproduction of the problem with instructions**
*STEPS TO REPRODUCE*
1. Install vue-toast-notification on a nuxt + vite project using bun
2. Run dev server 
3. Read the error.

I can create a minimal repo to reproduce the problem if needed.

**Comment by ankurk91** [comment]
Sorry i cant help in this
