### ISSUE TITLE
FR: Fade duration

### ISSUE THREAD

**Issue by mystyq** [ankurk91/vue-toast-notification#99]
```
[ ] Bug report => search github for a similar issue or PR before submitting
[x] Feature request
[ ] Other, please describe
```

**Tell about your platform**

* Vue.js version : 3.2.x
* Browser name and version : Chrome|Firefox|Edge x.x.x
* This package version : 3.x

**Current behavior**
Toast duration fades quickly and abruptly

**Expected behavior**
Implement a transition property to allow the opacity to be faded in or out for a specified time

**Comment by ankurk91** [comment]
Not relevant
